[versions]
arrow = "2.2.1.1"
commonsNet = "3.12.0"
commonsText = "1.15.0"
jsoup = "1.22.1"
kermit = "2.0.8"
koin = "4.1.1"
kord = "0.17.0"
kotest = "6.1.3"
kotlin = "2.3.10"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxSerialization = "1.10.0"
ktlint = "14.0.1"
# pin before kord fixes base64 decoding
ktor = "3.3.3"
logback = "1.5.28"
sentry = "6.0.0"
shadow = "9.3.1"
skrapeit = "1.3.0-alpha.2"
sqldelight = "2.2.1"
xalan = "2.7.3"

[libraries]
arrow-bom = { module = "io.arrow-kt:arrow-stack", version.ref = "arrow" }
arrow-core = { module = "io.arrow-kt:arrow-core" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience" }
commons-net = { module = "commons-net:commons-net", version.ref = "commonsNet" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-test-junit5 = { module = "io.insert-koin:koin-test-junit5" }
kord-common = { module = "dev.kord:kord-common", version.ref = "kord" }
kord-core = { module = "dev.kord:kord-core", version.ref = "kord" }
kord-rest = { module = "dev.kord:kord-rest", version.ref = "kord" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-statusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
skrapeit = { module = "it.skrape:skrapeit", version.ref = "skrapeit" }
sqldelight-driver-sqlite = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
xalan = { module = "xalan:xalan", version.ref = "xalan" }

[bundles]
arrow = [
    "arrow-core",
    "arrow-fx-coroutines",
    "arrow-resilience",
]
koin-test = [
    "koin-test",
    "koin-test-junit5",
]
kord = [
    "kord-common",
    "kord-core",
    "kord-rest",
]
kotest = [
    "kotest-assertions-core",
    "kotest-runner-junit5",
]
ktor-client = [
    "ktor-client-cio",
    "ktor-client-core",
    "ktor-client-encoding",
    "ktor-client-logging",
    "ktor-client-okhttp",
]
ktor-server = [
    "ktor-server-auth",
    "ktor-server-cio",
    "ktor-server-core",
    "ktor-server-statusPages",
]
skrapeit-overrides = [
    "commons-net",
    "commons-text",
    "jsoup",
    "logback-classic",
    "logback-core",
    "xalan",
]

[plugins]
application = { id = "application" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
sentry = { id = "io.sentry.jvm.gradle", version.ref = "sentry" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
versionCatalogUpdate = "nl.littlerobots.version-catalog-update:1.0.1"
